version: '3.8'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event_php
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=postgresql://postgres:root@db:5432/event_reservation?serverVersion=16&charset=utf8
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - app_network
  nginx:
    image: nginx:alpine
    container_name: event_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - app_network
  db:
    image: postgres:15-alpine
    container_name: event_db
    environment:
      - POSTGRES_DB=event_reservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: